services:
  broker:
    image: apache/kafka:3.9.0
    depends_on:
      - pgsql
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - list-sync-net
  pgsql:
    build:
      context: docker/pgsql
      dockerfile: Dockerfile
    container_name: pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - list-sync-net
  producer:
    build:
      context: docker/python
      dockerfile: Dockerfile
    depends_on:
      - broker
    volumes:
      - type: bind
        read_only: false
        source: ./python/kafka-project
        target: /app
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python src/pgsql_connector.py"
    networks:
      - list-sync-net
  consumer:
    restart: always
    build:
      context: docker/python
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    privileged: true
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.limit=20mbit"
      - "com.docker-tc.delay=100ms"
    volumes:
      - type: bind
        read_only: false
        source: ./python/kafka-project
        target: /app
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python src/consumer.py"
    networks:
      - list-sync-net

volumes:
  pgdata:

networks:
  list-sync-net:
    driver: bridge
