services:
  db-mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - list-sync-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  producer-mysql:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      db-mysql:
        condition: service_healthy
    volumes:
      - type: bind
        read_only: false
        source: ./python/pystream/connector
        target: /app/pystream/connector
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python pystream/connector/mysql_connector.py"
    networks:
      - list-sync-net

volumes:
  mysql_data:

networks:
  list-sync-net:
    driver: bridge
