services:
  consumer-pg:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 10
    privileged: true
    volumes:
      - type: bind
        read_only: false
        source: ./list_sync
        target: /app/list_sync
        bind:
          propagation: shared
          selinux: z
      - type: bind
        read_only: false
        source: ./test/data
        target: /app/test/data
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python list_sync/consumer/consumer.py simulate wal_pg no-file"
    networks:
      - list_sync-net

networks:
  list_sync-net:
    driver: bridge
