services:
  db-pgsql:
    build:
      context: pgsql
      dockerfile: Dockerfile
    container_name: pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - list_sync-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  producer-pgsql:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db-pgsql:
        condition: service_healthy
    volumes:
      - type: bind
        read_only: false
        source: ./list_sync/connector
        target: /app/list_sync/connector
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python list_sync/connector/pgsql_connector.py"
    networks:
      - list_sync-net

volumes:
  pgdata:

networks:
  list_sync-net:
    driver: bridge
