services:
  db-pgsql:
    build:
      context: pgsql
      dockerfile: Dockerfile
    container_name: pgsql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - list-sync-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  producer-pgsql:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      db-pgsql:
        condition: service_healthy
    volumes:
      - type: bind
        read_only: false
        source: ./python/pystream/connector
        target: /app/pystream/connector
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python pystream/connector/pgsql_connector.py"
    networks:
      - list-sync-net
  consumer-pg:
    build:
      context: ./python
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    privileged: true
    volumes:
      - type: bind
        read_only: false
        source: ./python/pystream
        target: /app/pystream
        bind:
          propagation: shared
          selinux: z
      - type: bind
        read_only: false
        source: ./python/test/data
        target: /app/test/data
        bind:
          propagation: shared
          selinux: z
    working_dir: /app
    command: "poetry run python pystream/consumer/__init__.py simulate wal_pg"
    networks:
      - list-sync-net



volumes:
  pgdata:

networks:
  list-sync-net:
    driver: bridge
